# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 3m
  tests: true

issues:
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  exclude-dirs:
    - "abi-bindings/go"
  exclude-files:
    - ".*mock.*"

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - whitespace
    - lll

linters-settings:
  gofmt:
    simplify: true
