name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  solhint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout teleporter
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install solhint
        run: |
          npm install solhint -g
          solhint --version

      - name: Run Lint
        run: ./scripts/lint.sh --sol-lint

  format-solidity:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        run: ./scripts/install_foundry.sh

      - name: Check Solidity Formatting
        run: |
          export PATH=$PATH:$HOME/.foundry/bin
          ./scripts/lint.sh --sol-format-check
